In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
df1 = pd.read_csv('Chapters.csv', encoding='latin-1')

In [3]:
df2 = pd.read_csv('WorldCupMatches.csv', encoding='latin-1')

In [4]:
df1 .head()

   Chapter ID         Chapter Name  Movie ID  Movie Chapter
0           1    Doorstep Delivery         1              1
1           2  The Vanishing Glass         1              2
2           3  Letters from No One         1              3
3           4   Keeper of the Keys         1              4
4           5         Diagon Alley         1              5

In [5]:
df2 .head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

In [6]:
import pandas as pd

# Read the dataframes
df1 = pd.read_csv('Chapters.csv', encoding='latin-1')
df2 = pd.read_csv('WorldCupMatches.csv', encoding='latin-1')

# Find the common columns
common_columns = df1.columns.intersection(df2.columns).tolist()

# Display the common columns
print("Common Columns:", common_columns)

Common Columns: []

In [7]:
# Print column names
print("Columns in df1:", df1.columns)
print("Columns in df2:", df2.columns)

# Print data types
print("Data types in df1:", df1.dtypes)
print("Data types in df2:", df2.dtypes)

# Check if dataframes are empty
print("Is df1 empty?", df1.empty)
print("Is df2 empty?", df2.empty)

Columns in df1: Index(['Chapter ID', 'Chapter Name', 'Movie ID', 'Movie Chapter'], dtype='object')
Columns in df2: Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')
Data types in df1: Chapter ID        int64
Chapter Name     object
Movie ID          int64
Movie Chapter     int64
dtype: object
Data types in df2: Year                      int64
Datetime                 object
Stage                    object
Stadium                  object
City                     object
Home Team Name           object
Home Team Goals           int64
Away Team Goals           int64
Away Team Name           object
Win conditions           object
Attendance              float64
Half-time Home Goals      int64
Half-time Away Goals      int64
Referee                  object
Assistant 1              object
Assistant 2              object
RoundID                   int64
MatchID                   int64
Home Team Initials       object
Away Team Initials       object
dtype: object
Is df1 empty? False
Is df2 empty? False

In [8]:
# Choose common columns with integer data types
common_columns_int = df1.select_dtypes(include='int64').columns.intersection(df2.select_dtypes(include='int64').columns).tolist()

# Display the common columns with integer data types
print("Common Columns with Integer Data Types:", common_columns_int)

Common Columns with Integer Data Types: []

In [9]:
# Print the first few rows of each dataframe
print("First few rows in df1:")
print(df1.head())

print("\nFirst few rows in df2:")
print(df2.head())

First few rows in df1:
   Chapter ID         Chapter Name  Movie ID  Movie Chapter
0           1    Doorstep Delivery         1              1
1           2  The Vanishing Glass         1              2
2           3  Letters from No One         1              3
3           4   Keeper of the Keys         1              4
4           5         Diagon Alley         1              5

First few rows in df2:
   Year              Datetime    Stage         Stadium         City  \
0  1930  13 Jul 1930 - 15:00   Group 1         Pocitos  Montevideo
1  1930  13 Jul 1930 - 15:00   Group 4  Parque Central  Montevideo
2  1930  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo
3  1930  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo
4  1930  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0         France                4                1         Mexico
1            USA                3                0        Belgium
2     Yugoslavia                2                1         Brazil
3        Romania                3                1           Peru
4      Argentina                1                0         France

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
0                     4444.0                     3                     0
1                    18346.0                     2                     0
2                    24059.0                     2                     0
3                     2549.0                     1                     0
4                    23409.0                     0                     0

                  Referee               Assistant 1  \
0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)
1       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)
2     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)
3   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)
4     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)

                  Assistant 2  RoundID  MatchID Home Team Initials  \
0         REGO Gilberto (BRA)      201     1096                FRA
1       WARNKEN Alberto (CHI)      201     1090                USA
2         BALWAY Thomas (FRA)      201     1093                YUG
3    MATEUCCI Francisco (URU)      201     1098                ROU
4  RADULESCU Constantin (ROU)      201     1085                ARG

  Away Team Initials
0                MEX
1                BEL
2                BRA
3                PER
4                FRA

In [10]:
# Resetting indices to use default integer indices
df1_reset = df1.reset_index()
df2_reset = df2.reset_index()

# Merging dataframes on the default integer index
merged_df = pd.merge(df1_reset, df2_reset, how='inner', left_index=True, right_index=True)

# Display the merged dataframe
print(merged_df)

     index_x  Chapter ID          Chapter Name  Movie ID  Movie Chapter  \
0          0           1     Doorstep Delivery         1              1
1          1           2   The Vanishing Glass         1              2
2          2           3   Letters from No One         1              3
3          3           4    Keeper of the Keys         1              4
4          4           5          Diagon Alley         1              5
..       ...         ...                   ...       ...            ...
229      229         230      Declare Yourself         8             22
230      230         231              Not Over         8             23
231      231         232     The Wand's Choice         8             24
232      232         233   The Wizard's Choice         8             25
233      233         234  Nineteen Years Later         8             26

     index_y  Year               Datetime                  Stage  \
0          0  1930   13 Jul 1930 - 15:00                 Group 1
1          1  1930   13 Jul 1930 - 15:00                 Group 4
2          2  1930   14 Jul 1930 - 12:45                 Group 2
3          3  1930   14 Jul 1930 - 14:50                 Group 3
4          4  1930   15 Jul 1930 - 16:00                 Group 1
..       ...   ...                    ...                    ...
229      229  1970  17 June 1970 - 16:00             Semi-finals
230      230  1970   20 Jun 1970 - 16:00   Match for third place
231      231  1970   21 Jun 1970 - 12:00                   Final
232      232  1974   13 Jun 1974 - 17:00                 Group 2
233      233  1974   14 Jun 1974 - 16:00                 Group 1

            Stadium  ... Attendance Half-time Home Goals  \
0           Pocitos  ...     4444.0                    3
1    Parque Central  ...    18346.0                    2
2    Parque Central  ...    24059.0                    2
3           Pocitos  ...     2549.0                    1
4    Parque Central  ...    23409.0                    0
..              ...  ...        ...                  ...
229  Estadio Azteca  ...   102444.0                    0
230  Estadio Azteca  ...   104403.0                    1
231  Estadio Azteca  ...   107412.0                    1
232     Waldstadion  ...    62000.0                    0
233  Olympiastadion  ...    81100.0                    1

     Half-time Away Goals                          Referee  \
0                       0           LOMBARDI Domingo (URU)
1                       0                MACIAS Jose (ARG)
2                       0              TEJADA Anibal (URU)
3                       0            WARNKEN Alberto (CHI)
4                       0              REGO Gilberto (BRA)
..                    ...                              ...
229                     0  YAMASAKI MALDONADO Arturo (MEX)
230                     0          SBARDELLA Antonio (ITA)
231                     1           GLOECKNER Rudolf (GDR)
232                     0             SCHEURER Ruedi (SUI)
233                     0              BABACAN Dogan (TUR)

                      Assistant 1                    Assistant 2  RoundID  \
0           CRISTOPHE Henry (BEL)            REGO Gilberto (BRA)      201
1        MATEUCCI Francisco (URU)          WARNKEN Alberto (CHI)      201
2         VALLARINO Ricardo (URU)            BALWAY Thomas (FRA)      201
3             LANGENUS Jean (BEL)       MATEUCCI Francisco (URU)      201
4            SAUCEDO Ulises (BOL)     RADULESCU Constantin (ROU)      201
..                            ...                            ...      ...
229  HORMAZABAL DIAZ Rafael (CHI)      VELASQUEZ Guillermo (COL)      569
230     MARSCHALL Ferdinand (AUT)    AGUILAR ELIZALDE Abel (MEX)     3477
231          SCHEURER Ruedi (SUI)  COEREZZA Norberto Angel (ARG)     3476
232            LORAUX Vital (BEL)           PESTARINO Luis (ARG)      262
233             TAYLOR John (ENG)         WINSEMANN Werner (CAN)      262

     MatchID  Home Team Initials Away Team Initials
0       1096                 FRA                MEX
1       1090                 USA                BEL
2       1093                 YUG                BRA
3       1098                 ROU                PER
4       1085                 ARG                FRA
..       ...                 ...                ...
229     1838                 ITA                FRG
230     1843                 FRG                URU
231     1765                 BRA                ITA
232     1986                 BRA                YUG
233     2003                 FRG                CHI

[234 rows x 26 columns]

In [11]:
# Check for missing values
print("Missing values in merged_df:")
print(merged_df.isnull().sum())

# Handle missing values (example: fill with mean)
merged_df.fillna(merged_df.mean(), inplace=True)

Missing values in merged_df:
index_x                 0
Chapter ID              0
Chapter Name            0
Movie ID                0
Movie Chapter           0
index_y                 0
Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

TypeError: Could not convert ["Doorstep DeliveryThe Vanishing GlassLetters from No OneKeeper of the KeysDiagon AlleyGringottsOllivandersThe Boy Who LivedPlatform 9&¾Ron and HermioneWelcome to HogwartsThe Sorting HatNick and Other ResidentsPotions and ParcelsNew SeekerThree-Headed SentinelFacts and FeathersMountain TrollQuidditchInterference OvercomeChristmas GiftCloaked in darknessThe Mirror of ErisedNorbertThe Forbidden ForestUp to SomethingThrough the TrapdoorWizard's ChessSacrifice PlayMan With Two FacesMagic TouchMark of LoveHouse Cup WinnerNot Really Going HomeIn a CageDobby's WarningCar RescueThe BurrowTo Diagon AlleyFlourish and BlottsFlying to HogwartsWhomping WillowNot Expelled... TodayMandrakes; Ron's HowlerGilderoy LockhartMudbloods and MurmursWriting on the WallAbout the ChamberRogue BludgerNo Longer SafeDueling ClubA ParselmouthNothing to TellPolyjuice PotionHarry and Ron TransformedThe DiaryTom RiddlePetrifiedCornelius FudgeAragogSpider AttackMissingChamber of SecretsBackfireHeir of SlytherinThe BasiliskHealing PowersOut Of The HatDobby's RewardWelcome BackUnder Covers PrologueAunt Marge's Big MistakeThe Knight BusThe Leaky CauldronIn Grave DangerThe DementorWelcome and WarningTea LeavesBuckbeakBoggart in the WardrobeTalent for TroubleFlight of the Fat LadySubstitute TeacherGrim DefeatThe Marauder's MapWho's There?I Hope He Finds MeThe PatronusSeeing the ImpossibleProfessor Trelawney's PredictionWitnesses to an ExecutionThe Whomping WillowSirius BlackPeter PettigrewFriends Become FoesThe Dementor's KissHermione's SecretOnlookers to the RescueSaving LivesTruly Seen, Truly FreeTwo Places at OnceMischief ManagedThe FireboltThe Riddle HouseThe PortkeyThe Quidditch World CupThe Dark MarkThe Triwizard TournamentThe Unforgivable CursesThe Four ChampionsLet Events UnfoldRita SkeeterSirius ConversationThe Hungarian HorntailTransforming MalfoyThe First TaskBest Foot ForwardAn Unexpected ChallengeThe Yule BallThe Egg's ClueThe Second TaskNever Whole AgainThe PensieveDreams and SuspicionsThe Third TaskFlesh, Blood and BoneThe Death EatersPriori IncantatemVeritaserumParting WaysDudley DementedThe Advance GuardNumber Twelve, Grimmauld PlaceThe Order of the PhoenixThe Ministry of MagicThe HearingThe OriginalsLuna LovegoodPreserve, Perfect and PruneProfessor Umbridge's ClassDetention With DoloresThe Hogwarts High InquisitorIn the Hog's HeadDumbledore's ArmyHagrid's TaleOcclumencyUnquiet EscapeGrawpSnape's Worst MemoryOut of the FireFight and FlightThe Department of MysteriesBeyond the VeilSide by SideWizards DuelThe Lost ProphecyA Way of Coming BackSnape's VisitorsWho's Harry Potter?Horace SlughornWhat Could Be Safer?That's For My FatherDark ForcesThe Half Blood PrinceThe Secret RiddleHermione's Helping HandCursed NecklaceSlug ClubFelix FelicisHow It FeelsFree AgentsThe Unbreakable VowDeath Eaters AttackSluggish MemoryPerilous PotionsSectumsempraHiding the BookLiquid LuckAfter Aragog's BurialHorcruxesThe Astronomy TowerFlight of the PrinceR.A.B.Dark TimesDark Lord AscendingThe Seven PottersAerial AmbushFallen WarriorDumbledore's WillThe WeddingPlace to HideKreacher's TaleTheft of a ThiefMinistry InteriorForest FugitivesGetting Too CloseBroken RanksClues RevealedGodric's HollowBathilda's SecretSword of GryffindorLighting the Way BackThe Three BrothersThe Deathly HallowsSnatchers StrikeMalfoy ManorDobby Has No MasterSleeping FriendShell CottageGriphook's PriceHe's After YouGringottsCopping the CupExit the DragonFinal Hiding PlaceAberforth DumbledoreHogwarts ReunionGive Me Harry PotterDuty To Our SchoolYou Need Only AskBlow For BlowFinding the DiademFiendfyreHe Will Come To MeYour Mother's EyesConfront Your FateI Open At the CloseThe Boy Who LivedKing's CrossDeclare YourselfNot OverThe Wand's ChoiceThe Wizard's ChoiceNineteen Years Later"] to numeric

In [12]:
# Select only numeric columns
numeric_columns = merged_df.select_dtypes(include='number').columns

# Fill missing values in numeric columns with the mean
merged_df[numeric_columns] = merged_df[numeric_columns].fillna(merged_df[numeric_columns].mean())

In [13]:
# Print column names for both dataframes
print("Columns in df1:", df1.columns)
print("Columns in df2:", df2.columns)

Columns in df1: Index(['Chapter ID', 'Chapter Name', 'Movie ID', 'Movie Chapter'], dtype='object')
Columns in df2: Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

In [14]:
print("Unique values in df1['Chapter ID']:", df1['Chapter ID'].unique())
print("Unique values in df2['Year']:", df2['Year'].unique())

Unique values in df1['Chapter ID']: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234]
Unique values in df2['Year']: [1930 1934 1938 1950 1954 1958 1962 1966 1970 1974 1978 1982 1986 1990
 1994 1998 2002 2006 2010 2014]

In [15]:
df2=pd.DataFrame(df2)
df2.rename(columns={'City':' Chapter ID'},inplace=True)
print("\nDataFrame after renaming the column:")
print(df2)

DataFrame after renaming the column:
     Year              Datetime                     Stage  \
0    1930  13 Jul 1930 - 15:00                    Group 1
1    1930  13 Jul 1930 - 15:00                    Group 4
2    1930  14 Jul 1930 - 12:45                    Group 2
3    1930  14 Jul 1930 - 14:50                    Group 3
4    1930  15 Jul 1930 - 16:00                    Group 1
..    ...                   ...                       ...
847  2014  05 Jul 2014 - 17:00             Quarter-finals
848  2014  08 Jul 2014 - 17:00                Semi-finals
849  2014  09 Jul 2014 - 17:00                Semi-finals
850  2014  12 Jul 2014 - 17:00   Play-off for third place
851  2014  13 Jul 2014 - 16:00                      Final

                 Stadium       Chapter ID Home Team Name  Home Team Goals  \
0                Pocitos      Montevideo          France                4
1         Parque Central      Montevideo             USA                3
2         Parque Central      Montevideo      Yugoslavia                2
3                Pocitos      Montevideo         Romania                3
4         Parque Central      Montevideo       Argentina                1
..                   ...              ...            ...              ...
847     Arena Fonte Nova        Salvador     Netherlands                0
848     Estadio Mineirao  Belo Horizonte          Brazil                1
849   Arena de Sao Paulo       Sao Paulo     Netherlands                0
850     Estadio Nacional        Brasilia          Brazil                0
851  Estadio do Maracana  Rio De Janeiro         Germany                1

     Away Team Goals Away Team Name                         Win conditions  \
0                  1         Mexico
1                  0        Belgium
2                  1         Brazil
3                  1           Peru
4                  0         France
..               ...            ...                                    ...
847                0     Costa Rica  Netherlands win on penalties (4 - 3)
848                7        Germany
849                0      Argentina    Argentina win on penalties (2 - 4)
850                3    Netherlands
851                0      Argentina          Germany win after extra time

     Attendance  Half-time Home Goals  Half-time Away Goals  \
0        4444.0                     3                     0
1       18346.0                     2                     0
2       24059.0                     2                     0
3        2549.0                     1                     0
4       23409.0                     0                     0
..          ...                   ...                   ...
847     51179.0                     0                     0
848     58141.0                     0                     5
849     63267.0                     0                     0
850     68034.0                     0                     2
851     74738.0                     0                     0

                    Referee                  Assistant 1  \
0    LOMBARDI Domingo (URU)        CRISTOPHE Henry (BEL)
1         MACIAS Jose (ARG)     MATEUCCI Francisco (URU)
2       TEJADA Anibal (URU)      VALLARINO Ricardo (URU)
3     WARNKEN Alberto (CHI)          LANGENUS Jean (BEL)
4       REGO Gilberto (BRA)         SAUCEDO Ulises (BOL)
..                      ...                          ...
847   Ravshan IRMATOV (UZB)  RASULOV Abduxamidullo (UZB)
848   RODRIGUEZ Marco (MEX)      TORRENTERA Marvin (MEX)
849  Cï¿½neyt ï¿½AKIR (TUR)         DURAN Bahattin (TUR)
850   HAIMOUDI Djamel (ALG)         ACHIK Redouane (MAR)
851    Nicola RIZZOLI (ITA)        Renato FAVERANI (ITA)

                    Assistant 2  RoundID    MatchID Home Team Initials  \
0           REGO Gilberto (BRA)      201       1096                FRA
1         WARNKEN Alberto (CHI)      201       1090                USA
2           BALWAY Thomas (FRA)      201       1093                YUG
3      MATEUCCI Francisco (URU)      201       1098                ROU
4    RADULESCU Constantin (ROU)      201       1085                ARG
..                          ...      ...        ...                ...
847    KOCHKAROV Bakhadyr (KGZ)   255953  300186488                NED
848       QUINTERO Marcos (MEX)   255955  300186474                BRA
849           ONGUN Tarik (TUR)   255955  300186490                NED
850     ETCHIALI Abdelhak (ALG)   255957  300186502                BRA
851        Andrea STEFANI (ITA)   255959  300186501                GER

    Away Team Initials
0                  MEX
1                  BEL
2                  BRA
3                  PER
4                  FRA
..                 ...
847                CRC
848                GER
849                ARG
850                NED
851                ARG

[852 rows x 20 columns]

In [16]:
import pandas as pd

# Read the dataframes
df1 = pd.read_csv('Chapters.csv', encoding='latin-1')
df2 = pd.read_csv('WorldCupMatches.csv', encoding='latin-1')

# Find the common columns
common_columns = df1.columns.intersection(df2.columns).tolist()

# Display the common columns
print("Common Columns:", common_columns)

Common Columns: []

In [17]:
#Display the first few rows of the combined dataset
print("First few rows of the df1,df2 dataset")
print(df1,df2.head())

First few rows of the df1,df2 dataset
     Chapter ID          Chapter Name  Movie ID  Movie Chapter
0             1     Doorstep Delivery         1              1
1             2   The Vanishing Glass         1              2
2             3   Letters from No One         1              3
3             4    Keeper of the Keys         1              4
4             5          Diagon Alley         1              5
..          ...                   ...       ...            ...
229         230      Declare Yourself         8             22
230         231              Not Over         8             23
231         232     The Wand's Choice         8             24
232         233   The Wizard's Choice         8             25
233         234  Nineteen Years Later         8             26

[234 rows x 4 columns]    Year              Datetime    Stage         Stadium         City  \
0  1930  13 Jul 1930 - 15:00   Group 1         Pocitos  Montevideo
1  1930  13 Jul 1930 - 15:00   Group 4  Parque Central  Montevideo
2  1930  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo
3  1930  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo
4  1930  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0         France                4                1         Mexico
1            USA                3                0        Belgium
2     Yugoslavia                2                1         Brazil
3        Romania                3                1           Peru
4      Argentina                1                0         France

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
0                     4444.0                     3                     0
1                    18346.0                     2                     0
2                    24059.0                     2                     0
3                     2549.0                     1                     0
4                    23409.0                     0                     0

                  Referee               Assistant 1  \
0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)
1       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)
2     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)
3   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)
4     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)

                  Assistant 2  RoundID  MatchID Home Team Initials  \
0         REGO Gilberto (BRA)      201     1096                FRA
1       WARNKEN Alberto (CHI)      201     1090                USA
2         BALWAY Thomas (FRA)      201     1093                YUG
3    MATEUCCI Francisco (URU)      201     1098                ROU
4  RADULESCU Constantin (ROU)      201     1085                ARG

  Away Team Initials
0                MEX
1                BEL
2                BRA
3                PER
4                FRA